year=input()
month=input()
date=input()
print(year,month,date)
print(year,month,date,sep='-')
print(year,month,date,sep='/')
print(month,date,year,sep=',')
# str.format()
print("{}年{}月{}日".format(year,month,date))
print(year+"年"+month+"月"+date+"日")